// ===============================================================
// projects.tsx — Specific roles, contributions, and links to real work.
// ===============================================================
import { ArrowUpRight } from 'lucide-react';
const projects = [
  { title: 'Supermarket management system', role: 'Software developer', description: 'I visited stores to understand how they handle stock and sales, then used that research to guide a supermarket management project.', tasks: ['Researched store workflows in person.', 'Worked on product records, stock levels, sales, restocking, and reports.'], technologies: 'Node.js · Express · MongoDB', href: 'https://github.com/Your-Boy-Josiah/Super-store-Management', label: 'View code' },
  { title: 'Personal finance tracker', role: 'Lead project manager', description: 'I organised the team, assigned tasks, reviewed code, and fixed bugs in an application for tracking income, expenses, and budgets.', tasks: ['Set up the folder structure and Git branches.', 'Reviewed team members’ code and fixed most of the bugs.', 'Wrote code comments and helped keep the project organised.'], technologies: 'React · Node.js · MongoDB', href: 'https://github.com/Your-Boy-Josiah/-personal-finance-tracker-', label: 'View code', preview: '/images/finance-dashboard.png' },
  { title: '12 kVA solar installation', role: 'Co-lead engineer', description: 'I co-led the design and installation of a solar power system serving 10 university student hostels.', tasks: ['Handled load calculations, battery layouts, and inverter configurations.', 'Worked on procurement, mounting, and electrical integration.'], technologies: 'Solar power · Electrical integration', href: '/documents/josiah-ewumi-cv.pdf', label: 'Read in my CV' },
  { title: 'LASU student mental-health programme', role: 'Lead project / program manager', description: 'I led a mental-health and depression-awareness programme for LASU students through Project Management Circle, which I co-founded.', tasks: ['Led a programme focused on student support and access to counselling.', 'Combined programme leadership with my role as PMC co-founder.'], technologies: 'Program management · Student support', href: '/documents/josiah-ewumi-cv.pdf', label: 'Read in my CV' },
  { title: 'Personal link-tree website', role: 'Software developer', description: 'This website brings my projects, CV, and social links together. Its backend counts social-link visits and lets me choose which links are public.', tasks: ['Developed the public page and owner dashboard.', 'Added link visibility controls, click tracking, and direct contact links.'], technologies: 'React · TypeScript · Cloudflare D1', href: 'https://github.com/Your-Boy-Josiah/link-tree-', label: 'View code' },
];
export default function Projects() {
  return <section className="projects-section" id="projects" aria-labelledby="projects-title"><div className="section-heading"><h2 id="projects-title">Projects I&apos;ve worked on</h2><p>My role and what I contributed</p></div><div className="project-list">{projects.map(project => <article className="project-row" key={project.title}><div className="project-main"><p className="project-role">{project.role}</p><h3>{project.title}</h3><p>{project.description}</p><details className="project-details"><summary>More about my contribution</summary><ul>{project.tasks.map(task => <li key={task}>{task}</li>)}</ul>{project.preview && <a className="preview-link" href={project.preview} target="_blank" rel="noopener noreferrer"><img src={project.preview} alt="Personal finance tracker dashboard showing financial summaries and budget information" width="1000" height="600" loading="lazy" /><span>Open dashboard screenshot</span></a>}</details></div><div className="project-side"><p>{project.technologies}</p><a className="text-action" href={project.href} target="_blank" rel="noopener noreferrer" aria-label={project.label + ' for ' + project.title + ', opens in a new tab'}>{project.label}<ArrowUpRight size={17} aria-hidden="true" /></a></div></article>)}</div></section>;
}



